version: "3.10.11"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    image: app:django
    container_name: snap_sort
    command: python3 backend/manage.py runserver 0.0.0.0:8080
