# version: "3.10.11"
# services:
#   app:
#     build: ./app
#     ports:
#       - 8080:8080
#     volumes:
#       - ./app/:usr/src/app/
#     image: app:django
#     container_name: snap_sort
#     command: python3 manage.py runserver 0.0.0.0:8080

version: '3'

services:
  django_gunicorn:
    volumes:
      - static:/static
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes: 
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: